### ISSUE TITLE
Should we extract bee-common out of the bee repository ?

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/bee#896]

**Comment by pvdrz** [comment]
My 2 cents here are the following:

- common crates should be (and some of them are) used in more than one branch. 
- given that they are supposedly common, the functionality of the common crates shouldn't change between branches. An extreme example of this is `bee_ord::is_unique_sorted`, do we need one version of `bee-ord` in each branch?
- there is an advantage if a vulnerability is caused by one of the common crates: if we kept the common crates in their own repo We should release a new minor/patch version for the major version fixing the vulnerability and then update the dependencies in the branches of the bee repo. If we keep the common crates in the bee repo we would have to fix the vulnerability independently for each branch.

**Comment by grtlr** [comment]
I think that this is a good idea from the developers perspective. The only downsides that I see are organizational:

* Having to set up and maintain an additional repository;
  * Finding a good name and description;
  * Duplicating CI workflows;
  * Potential duplication of issues because users wouldn't know where to file them;
  * Change of development practices have to be applied to two repositories; 
* An additional repository / project creates more indirection that might confuse new developers;
* Diffusion of knowledge;
  * Right now the Bee repository is a one-stop-shop for everything;
* Continuously moving crates over into new repository as things mature;

That being said, I'm not a huge fan of fragmentation but here it might be beneficial.

**Comment by samuel-rufi** [comment]
The cost of setting up and maintaining an additional repository is worth it in my opinion.
In the end, it might lead to less complexity and fragmentation if you take into account the points mentioned by @pvdrz

**Comment by pvdrz** [comment]
Regarding @grtlr comments:

> - Duplicating CI workflows;

Another change related to CI is that you're only checking/testing the parts of the project that you actually changed. Updating `bee-message` shouldn't have to run the workflows for the common crates. This also means that the common crates should have a more robust test suite. Otherwise bugs introduced in the common crates would only show once you bump the dependencies versions.

> - Potential duplication of issues because users wouldn't know where to file them;

Yeah but that could happen with any of our dependencies to be honest. As an hypothetical example,  if there was a performance issue in `CurlP` and as a consequence it is making bee slow, it might get reported in the bee tracker and we would have to escalate it to iota-crypto.

> - Change of development practices have to be applied to two repositories;

This could be taken as a positive thing as future changes to the branches of the `bee` repo (like `chrysalis-pt2` or `dev` disappearing) wouldn't affect the common crates and we wouldn't have to migrate features of the common crates between branches when removing them,

> - Diffusion of knowledge;
>   - Right now the Bee repository is a one-stop-shop for everything;

This is true but we don't actually share that knowledge as well as we could. Having everything in a single repo means we don't publish crates that often which at the same time means we pay less attention to the docs that get published and filling changelogs becomes harder given that we only publish crates and check for changes in the API when we want to use a bee crate in another branch, which would become less common once the cpt2 vs dev branches issue is solved.

> - Continuously moving crates over into new repository as things mature;

This is a burden but at the same time it could make the edit/compile/test cycle faster by having less crates to recompile due to changes in non-common crates.

**Comment by grtlr** [comment]
Thank you for writing this out—these are very good points. Overall I'm also in favor of creating a separate repository for `bee-common`. Maybe we can get @Dr-Electron on board for this discussion too?

**Comment by Adam-Gleave** [comment]
> - Diffusion of knowledge;
>   - Right now the Bee repository is a one-stop-shop for everything;

I feel this can be a bit of a double-edged sword. Smaller codebases are a bit easier to digest and get to grips with -- whereas a large repository like the main Bee project is a large effort to navigate and familiarise with if you're new. Having `bee-common` in it's own repository, whilst meaning that things are a bit more spread out, makes it clear that it's entirely self-contained, and can be understood without any real knowledge of the rest of the Bee project. There is an argument that this is already somewhat implied by it being its own crate, but many of the `bee-*` crates are not completely self-contained in this way.

I don't think this is without its downsides (a separate repository could make things a little hard to navigate, as @grtlr's second point, and testing local patch changes is maybe a bit inconvenient), I think the upside of eliminating the duplication we currently have is pretty attractive.

**Comment by Alex6323** [comment]
Having read through the whole discussion I saw very good points in favor (and against) whether `bee-common` should live in its own repo. I am - essentially - fine with whatever will be decided, but want to add something to the discussion - may it be helpful or not :trollface: It's more like a question than a statement, that I didn't find reflected enough in the points you guys made so far:

Correct me if I am wrong, but I think from a "metaphysical" slash "philosophical" standpoint I think a repo "should" represent a project with a design goal or with an idea behind. For `iota-crypto` this is obviously "providing the cryptographic functionality used in the IOTA realm", for Bee it's "Providing a set of tools to build nodes, and some default node implementations", and so on ...
Looking at the module structure of `bee-common` I can not find a coherent story/design goal for this crate:
```
pub mod auth;
pub mod logger;
pub mod ord;
pub mod packable;
pub mod time;
```
Again, correct me if I am wrong, but it looks more like a bunch of stuff grouped together by chance, that only have in "common" (pun intended), that they are used by more than one Bee crate, and needed a place to stay to prevent circular dependencies.

I can possibly see `packable` living in it's own repo. I don't know the other modules well enough to have an opinion on them.

**Comment by pvdrz** [comment]
I understand @Alex6323's point about the `bee-common` crate being an heterogeneous collection of unrelated modules but in my head, `bee-common` is "just" the repo where several common crates live. In a way, this `bee-common` repo is composed of things we miss from `std` (like `bee-time` and `bee-ord`) and just like the standard library I think it is ok for them to be unrelated.

**Comment by Dr-Electron** [comment]
Tbh I saw a lot of repos which are like a tool box for the most different stuff 🤔 
But I also like repos with a single purpose. So I get the point 😅 

So it could be a collection of tools enabled by "features".
I like the logger wrapper. I would probably also use it in other projects 😆

**Comment by thibault-martinez** [comment]
We agreed to do it, next step is https://github.com/iotaledger/bee/issues/952
