### ISSUE TITLE
Autopeering is slower than its hornet counterpart

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/bee#920]

**Comment by Alex6323** [comment]
Can you provide a little bit more detail? To come to this conclusion you would need at least 10 samples from both node implementations respectively to be somewhat on the statistical safe side. And even more importantly add to your description what's the start and end point of the measurement. I am assuming you mean the time it takes until a valid gossip peer has been connected and the node starts syncing!?.

Although I cannot reject your statement right away, I want you to consider the following things:
(a) autopeering is a probabilistic system by design: 
     - if we are queried we pick a random set of at most 6 peers to send in our discovery response; same goes for the remote peer.
     - each auto-peer creates 2 random salts (every 2 hours), by which distances to possible candidates are determined: when we (as a new peer) try to get integrated into the network possible peers very likely already have full neighborhoods, and would only accept us if we got "lucky" and are evaluated to have a shorter distance than their current furthest-away neighbor. If we're unlucky this can take some time.
 (b) autopeering in general is not supposed to work as fast as possible. For example: the time interval in which we query a peer (to discover new peers) is identical in Bee and Hornet and set to 60(!!!) seconds. Hence finding a suitable peer can take some time.

**Comment by Dr-Electron** [comment]
I will do some tests tonight. But most of the time it takes 3-6min for a peer to show op on the dashboard which !seemed! slower than it is in Hornet. As i said, i will investigate more

**Comment by Dr-Electron** [comment]
This are the results if I look at the logs. Start time was the autopeering start time and I stopped once I got a peer which send me new milestones.
But I think I made a mistake. Because if I stop and start the node to quickly the other peer may connect with me right at the beginning? Also bee seems to start the gossip plugin after auto peering but I think Hornet starts it before. So there could be a difference of some sec.
But in general you can see that sometimes Bee takes way longer to connect to its first peer. 
I didn't have too much time today. So I can do some more test sometime later if needed.

```
Hornet:
21:37:15Z	21:38:25Z  1m10s
21:51:40Z	21:52:59Z  1m19s
22:00:07Z	22:00:36Z  29s
22:02:18Z	22:04:07Z  1m49s
22:04:48Z	22:06:37Z  1m49s

Bee:
22:20:26    22:23:34  2m9s
22:33:15    22:38:23  5m8s
22:42:31    22:43:09  38s
22:45:11    22:45:20  9s
22:49:33    22:54:42  5m9s
```
