### ISSUE TITLE
Investigate Rust binary size reduction

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/bee#925]
By default, rust binaries are pretty big but can be reduced with some options.
https://www.reddit.com/r/rust/comments/rxnbu7/why_do_rust_executables_produce_such_huge_files/
https://www.reddit.com/r/rust/comments/rw0jad/cargos_strip_profile_option_has_been_stabilized/

**Comment by grtlr** [comment]
Our release profile currently looks like this:

```toml
[profile.release]
panic = "abort"
```

So I have created a profile `min-size` with the following settings:

```toml
[profile.min-size]
inherits = "release"
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"
```

These are the results:

```bash
du -h target/release/bee                                                                                                                                                                      
18M    target/release/bee

du -h target/min-size/bee                                                                                                                                                                     
9.3M    target/min-size/bee
```

That's quite a significant improvement I would say.

On the other hand, it's really hard to judge how that would influence the overall performance because we currently don't have extensive benchmarks.

There is also the more aggressive `opt-level = "z"`, which removes auto vectorization, but I think that would not be worth it.

Should I create a PR with the above profile? And if yes, this should probably go into `dev` and `chrysalis-pt2` right?

**Comment by pvdrz** [comment]
I think the profile @grtlr proposes is as good as it can be to optimize binary size. I'd investigate the `opt-level` flag though.

It also would be interesting to have a performance optimized profile so the most curious users can compile bee to squeeze as much performance as possible.

**Comment by grtlr** [comment]
I have created a `production` profile instead:

```toml
[profile.production]
codegen-units = 1
inherits = "release"
lto = true
panic = "abort"
strip = "symbols"
```

Which yields:

```bash
du -h target/production/bee                                                                                                                                                         
12M    target/production/bee
```
