### ISSUE TITLE
Fuzz not only Message

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/bee#939]
Even though every other types are reachable through `Message`, the fuzzer may take a very long time to reach, or even never reach, deeply nested types. We should fuzz them all independently.

**Comment by pvdrz** [comment]
Maybe this could be something built on top of `bee-packable` something like a new crate `bee-packable-fuzz` or a feature.

**Comment by pvdrz** [comment]
Sadly code generation capabilities for rust are not there yet. I was thinking we could generate the `fuzz` crate by tagging `Packable` types with a `#[packable(fuzz)]` tag or something and then generate an appropriate fuzz target file from it but the issue is that we cannot obtain the path required to import the type. For example, we cannot obtain the `bee_message::output::AliasOutput` path from the `AliasOutput` definition.

For now our best bet seems to be doing it the good ol' reliable way of writing it by hand.
