### ISSUE TITLE
Investigate SQL crate options

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/bee#971]

**Comment by grtlr** [comment]
Here is a little overview of what I've investigated over the last couple of days.

We probably want a database management system (DBMS) that supports ACID properties, because the database will store ledger state. If we go down the route of a relational model, we have basically two options for our DBMS:

  * PostgreSQL (fully-featured; lot's of customization)
  * SQLite (database is stored in a single file; lightweight)

It's important to note that there are also NoSQL databases, such as Neo4j (graph database), and key-value stores, which also satisfy ACID properties and could therefore be considered.

If we choose one of the two options above, we are presented with additional decitions to make. Namely, do we want a simple SQL driver or a full-fledged ORM? The following gives an overview of crates in those two spaces.

### SQL drivers (performs communication between database and node)

Usually require writing raw SQL code.

* [SQLx](https://crates.io/crates/sqlx)
  * Postgres, MySQL, and sqlite backends
  * Checked at compile time (by running against database)
  * offers migrations
  * async

* [postgres](https://crates.io/crates/postgres) & [sqlite](https://crates.io/crates/sqlite) (not async; but because of threadpools the consensus is that no big disadvantage)

* [tokio-postgres](https://crates.io/crates/tokio-postgres) (async)

* [quaint](https://crates.io/crates/quaint) (async)
  * Does not aim to be an ORM
  * but offers abstractions over multiple databases

### Object-relational mappers

Provide more convenience functions, such as migrations, or multiple database backends. Often provide type safety guarantees through SQL abstractions.

* [SeaORM](https://crates.io/crates/sea-orm)
  * async
  * very new project
  * builds upon SQLx
  * aims to be simpler than Diesel, more dynamic design

* [Diesel](https://crates.io/crates/diesel)
  * powerful and established
  * not async
  * heavily depends on template parameters; lot's of static checking

## Personal opinion

I don't think we should start with an ORM but rather choose an SQL driver. I think SQLx looks promising in that regard.

@rufsam @pvdrz

**Comment by pvdrz** [comment]
> I don't think we should start with an ORM but rather choose an SQL driver. I think SQLx looks promising in that regard.

I agree, being able to switch between different backends seems like something desirable.
